services:
  api:
    build: .
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DATABASE_NAME=lss_db
    depends_on:
      - mongo

  mongo:
    image: mongo:8
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
